# When action==teardown we destroy the existing configuration
action: setup

# Which libvirt session should we use?  Using `qemu://session` does
# not require privileged access (but does require the setup performed by the
# `environment/setup` role).
libvirt_volume_pool: oooq_pool
libvirt_domain_type: kvm
libvirt_diskdev: sda
libvirt_diskbus: scsi
libvirt_arch: x86_64
libvirt_cpu_mode: host-model

# how many disks should be created when using extradisks
extradisks_list:
  - vdb

# size of the disks to create when using extradisks
extradisks_size: 8G

# The packages required to set up our desired libvirt environment.
libvirt_packages:
  - qemu-kvm
  - libvirt
  - libvirt-python
  - libguestfs-tools
  - python-lxml
  - polkit-pkla-compat

# The name of the libvirt service.
libvirtd_service: libvirtd
