---
- name: Setup dummy baremetal VMs
  hosts: virthost
  connection: local
  gather_facts: true
  tasks:
    - import_role:
        name: common
    - import_role:
        name: libvirt
    - import_role:
        name: virtbmc/setup
      when: vm_platform == "libvirt"
