---
- name: Setup dummy baremetal VMs
  hosts: virthost
  connection: local
  gather_facts: true
  tasks:
    - import_role:
        name: common
    - import_role:
        name: environment/setup
    - import_role:
        name: libvirt/setup
      when: platform == "libvirt"
    - import_role:
        name: virtbmc/setup
      when: platform == "libvirt"

