---
# The `libvirt/setup` role creates the undercloud and overcloud
# virtual machines, note we only create the "overcloud" machines
# because the undercloud isn't needed in this environment
- name: Setup dummy baremetal VMs via tripleo-quickstart
  hosts: virthost
  connection: local
  gather_facts: true
  tasks:
    - import_role:
        name: common
    - import_role:
        name: environment/setup
    - import_role:
        name: libvirt/setup
      when: platform == "libvirt"
    - import_role:
        name: virtbmc/setup
      when: platform == "libvirt"

